### ISSUE TITLE
object-position not working on IEdge

### ISSUE THREAD

**Issue by ghost** [bfred-it/object-fit-images#15]
![image](https://cloud.githubusercontent.com/assets/11951600/15181732/1fe351d2-1789-11e6-8ae3-e27d0c2b1405.png)

Also, when I test the [demo website](http://bfred-it.github.io/object-fit-images/demo/) from my phone it says fix is unnecessary, but object-position does not work (both Safari and Chrome).

**Comment by bfred-it** [comment]
That's strange, caniuse says that it's not supported in edge until v13 (latest)
Can you verify what version you have exactly on your phone?

Either way it will be fixed as part of https://github.com/bfred-it/object-fit-images/issues/4

**Comment by fregante** [comment]
I assume you're testing on:
- mobile Safari, which will be fixed by https://github.com/bfred-it/object-fit-images/issues/4
- IE, which was fixed by https://github.com/bfred-it/object-fit-images/commit/0d28dec81f15158bfab170b92ae53c25c175c8ed in v2.3.3, `object-position` wasn't working correctly with percentages
