### ISSUE TITLE
Polyfill object-position where object-fit is supported (Safari)

### ISSUE THREAD

**Issue by fregante** [bfred-it/object-fit-images#4]
More info on #7 and https://github.com/bfred-it/object-fit-images/blob/gh-pages/detailed-support-tables.md#object-fit-images--srcset

**Comment by bfred-it** [comment]
More info on #7 and https://github.com/bfred-it/object-fit-images/blob/gh-pages/detailed-support-tables.md#object-fit-images--srcset

**Comment by bcole808** [comment]
+1 for `object-position` support in Safari! 

I see your note that adding object-position support to Safari could cause Safari to use `src` values instead of `srcset` -- it could be nice for this to be an optional feature that could be enabled if the developer decides that the trade off is worth it. 

For example on one of my websites, I would rather have `object-position` work than `srcset` because the positioning of the images matters more to me than the correct `srcset` image.

**Comment by fregante** [comment]
@amaldare93 @bcole808 @RobertCordes 

I added `object-position` support in Safari, you can try [v2.5](https://github.com/bfred-it/object-fit-images/compare/v2.4.2...gh-pages) and have a look at the [notes](https://github.com/bfred-it/object-fit-images/blob/gh-pages/detailed-support-tables.md#notes-about-specific-combinations)
